#! /bin/csh -f

# notes on running scripts for QC processes

#################################################################
# Environment is set in:

  ~/git/HCR_configuration/projDir/qc/scripts/set_env_qc

which sets up:

  PROJ_DIR = ~/git/HCR_configuration/projDir
  DATA_DIR = /scr/rain1/rsfdata/projects/socrates/hcr/qc

#################################################################
#
# Initial stages
#
# (1) analyze temperatures and powers from noise source cals (Rike)
#     Input data is in $DATA_DIR/temperatures1s
#                      $DATA_DIR/temperatures10s
#     Step (a): run TsStatusMonitor to produce SPDB files
#     Step (b): run SpdbXml2Table, to produce space-delimited text file
#               containing temps
#     Step (c): Run Matlab to read moments, correlate with temps.
#     Results file is: ????
#
# (2) Run HcrTempRxGain to compute gain change with temp (Mike)
#     Input data is time series in:
#       /scr/rain1/rsfdata/projects/socrates/hcr/time_series/wband/save
#     Output is XML stored in SPDB in:
#       $DATA_DIR/spdb/tempVsGain
#     This output was checked by Rike, comparing against Matlab plots

#################################################################
# Dsr2Radx - 100 hz
#
# Save out 100Hz moments files in CfRadial
# Open terminal
#
# NOTE: start this script first because it will wait for output
# from Iq2Dsr

cd ~/git/HCR_configuration/projDir/qc/scripts
./run_Dsr2Radx.qc.100hz

#################################################################
# Iq2Dsr
#
# This reads time series, computes moments, corrects gain for
# temperatures, writes 100hz moments data to FMQ (file message queue)
#
# Open terminal
# run

cd ~/git/HCR_configuration/projDir/qc/scripts
./run_Iq2Dsr.qc.100hz &
tail -f $DATA_DIR/logs/Iq2Dsr.qc.100hz

# NOTE: to kill this step run:

snuff ./run_Iq2Dsr.qc.100hz
snuff Iq2Dsr

#################################################################
# RadxMon - use to see moments are flowing
#
# Don't do this when re-processing the data, only as a test.
# Iq2Dsr is writing the FMQ in blocking mode, and only 1 reader is allowed
#
# Open terminal

# RadxMon -fmq /tmp/fmq/qc_moments/100hz/shmem_30100 -summary -update -5


