#! /bin/csh -f

# set up the environment for HCR QC processing

setenv PROJ_DIR ~/git/HCR_configuration/projDir
setenv DATA_DIR  /scr/rain1/rsfdata/projects/socrates/hcr

# make sure the output dirs exist

mkdir -p $DATA_DIR
mkdir -p $DATA_DIR/logs

# bring in the project info environment

source $PROJ_DIR/system/params/project_info


