function cloudFlag=middleCloudClass(cloudParams)
% Classify clouds into Middle clouds: Ns (2), Cu (3), Sc (4), St (5), As (6), Ac (7)
cloudFlag=nan;

if cloudParams.meanBaseTemp>-30 & ((cloudParams.meanMaxReflAgl<2.2 & cloudParams.maxAgl<3) | ...
        (cloudParams.meanMinAgl<2 & cloudParams.maxAgl<3) | ...
        (cloudParams.meanMinAgl<1.85 & cloudParams.maxAgl<4 & ...
        cloudParams.meanThickness<2 & cloudParams.meanMaxAgl<3.2))
    cloudFlag=4;
elseif cloudParams.meanMinAgl<2 & cloudParams.meanThickness<1 & ...
        (cloudParams.maxAgl-cloudParams.minAgl)<1.5 & cloudParams.meanBaseTemp>-30
    cloudFlag=5;
elseif cloudParams.meanMinAgl<1.2 & cloudParams.meanThickness>4.5 & cloudParams.lengthKM>52
    cloudFlag=2;
elseif cloudParams.meanBaseTemp>-30 & cloudParams.meanMinAgl<2 & cloudParams.meanMaxReflTemp>-5 % Cloudsat also uses MODIS cloud fraction
    cloudFlag=3;
elseif cloudParams.meanBaseTemp>-30 & ((cloudParams.meanMinAgl>1.8 & cloudParams.meanBaseTemp>5 ...
        & cloudParams.meanThickness<2.7 & cloudParams.meanMaxRefl<0) | ...
        (cloudParams.meanMinAgl>1.8 & cloudParams.meanMinAgl<7 & ...
        ((cloudParams.meanThickness<1.25 & cloudParams.meanMaxRefl<-10 & cloudParams.meanMaxReflTemp>-20) | ...
        (cloudParams.meanThickness<1.75 & cloudParams.meanMaxRefl<-10 & ...
        cloudParams.meanMaxReflTemp>-27 & cloudParams.minTopTemp>-35) | ...
        (cloudParams.meanThickness<2.5 & cloudParams.meanMaxRefl<-8 & cloudParams.minTopTemp>-22))) | ...
        ((cloudParams.meanMaxRefl+cloudParams.stdMaxRefl)>0 & ...
        (cloudParams.meanMaxRefl-cloudParams.stdMaxRefl)<-15 & cloudParams.stdMinAgl>0.6 & ...
        cloudParams.meanMinAgl<5.5 & cloudParams.meanThickness<4 & ...
        cloudParams.minTopTemp<-30 & cloudParams.stdMaxAgl<0.6) | ...
        ((cloudParams.stdMinAgl/cloudParams.meanThickness)>0.5 & cloudParams.monTopTemp>-5) | ...
        (cloudParams.meanThickness<1 | cloudParams.minTopTemp>2) | ... % Cloudsat also uses MODIS cloud fraction
        (((cloudParams.meanMinAgl<1.8 & cloudParams.stdMinAgl>0.6 & cloudParams.meanMaxRefl<-5) | ...
        (cloudParams.meanMinAgl<1.2 & cloudParams.stdMinAgl>0.48 & cloudParams.meanMaxRefl<-1.5)) & ...
        cloudParams.meanMaxAgl>3 & cloudParams.meanMaxAgl<8 & ...
        (cloudParams.lengthKM<100 | cloudParams.meanMaxRefl<-15)) | ...
        (cloudParams.meanMinAgl>1.7 & cloudParams.meanMaxAgl<8 & cloudParams.minTopTemp>-35 & ...
        (cloudParams.lengthKM<100 | cloudParams.meanMaxRefl<-3 | ...
        (cloudParams.stdMinAgl>1 & cloudParams.stdMaxAgl<0.3)) & ...
        ((cloudParams.minAgl<0.8 & cloudParams.stdMinAgl>0.48) | ...
        (cloudParams.minAgl<1.2 & cloudParams.stdMinAgl>0.57) | ...
        (cloudParams.minAgl<1.5 & cloudParams.stdMinAgl>0.9))))
    cloudFlag=7;
else
    cloudFlag=6;
end
end

