#! /bin/csh

# untar reanalysis files

setenv INDIR ./otrec
cd $INDIR

setenv FILES *.tar

#ls $FILES

foreach file ($FILES)
echo $file
tar -xvf $file
end

rm -f *.tar
rm -f Authentication.log
rm -f auth.rda_ucar_edu
rm -f download_ds*

